spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sports_booking_auth
    username: sportsapp
    password: sportsapp123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#hello

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.springframework.data: INFO
    com.sportschaos: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
